### PR TITLE
Use travis container architecture

### PR DESCRIPTION
**Pull request by jvc26**

### CODE REVIEW

**Comment by doismellburning** [comment]
Oof cripes. Really must remove that setup.py/requirements.txt combo of icky :s

**Comment by doismellburning** [comment]
(I'll tox this up with a bit of a test matrix for Django versions tonight)

**Comment by jvc26** [comment]
Yeah just came back to look at this and its a mess - pushed too early unfortunately, as there are some serious issues - wanted to update to 1.7 compatibility, but there are big problems with change in test runners. In addition, there is also something funny going on with timezone recognition, which also needs fixing.

**Comment by doismellburning** [comment]
Oof. Can you file what you have as issues? As I say, I'm very happy to poke more tonight!

**Comment by jvc26** [comment]
Yeah have been spinning them out into separate issues. Essentially currently there are problems from changes to test runners, and also the app loading changes from 1.6-1.7. The current testing script is far too inflexible to cope with this, and probably if we are to continue to support 1.6 and 1.7. I realise we don't support 1.4 (as far as I can tell), though the official 1.4 support ends in Mar 2015.

**Pull request closed without merging**
